### ISSUE TITLE
Error while running Hayai to annotate 1 gene

### ISSUE THREAD

**Issue by pierrelarmande** [kdri-genomics/Hayai-Annotation-Plants#3]
Hi Andrea,

I tried to run Hayai but got this error, sorry my Os is in French, I have mac OsX Mojave 10.14.2
Warning: Error in plot.window: 'xlim' nécessite des valeurs finies
  [No stack trace available]

**Comment by kdri-genomics** [comment]
hi Pierre,
thank you for your message. This problem happened because the number of query sequences were too low to make a graphic, it was fixed in the new version 'hayai_1.0.1.tar.gz'
