### ISSUE TITLE
Error finding usearch

### ISSUE THREAD

**Issue by pierrelarmande** [kdri-genomics/Hayai-Annotation-Plants#4]
I have installed usearch in os X on /usr/local/bin following the install recommendation.
It does not required to use ./usearch from its directory to run on my system, i use "usearch" wherever in the home directory.

However hayai runs usearch with "./usearch" which required to run it from its directory.

**Comment by kdri-genomics** [comment]
Pierre, thank you for your message. This problem was fixed in the new version hayai_1.0.1.tar.gz. Please, be aware that to install the new version, the database should be installed again, command 'db()'

**Comment by kdri-genomics** [comment]
Please let me know if there is any other problem. Thank you!
