### ISSUE TITLE
About the Interproscan result

### ISSUE THREAD

**Issue by yfuruta** [kdri-genomics/Hayai-Annotation-Plants#8]
Thank you so much for developping this great tool.
I'd like to inquire about the Interproscan run by Hayai_annotation_v2.0 web server.

Using the same protein multifasta file, I ran Interproscan 5.65-97.0 with default parameter setting and found that the results were slightly different from that produced by hayai_annotation_v2.0. Hayai_annotation_v2.0 detected more number of domains compared to my run, so my guess of the cause was lower cutoff value or some curation of the pfam database (or just the difference of the version of Interproscan...), but I couldn't find the detail information.

It would be great if you could tell me a bit more detail of the Interproscan of Hayai_annotation_v2.0.

Thanks!

**Comment by aghelfi** [comment]
Thank you for your inquiry.

Hayai-Annotation Plants v2, the web server version, implements as a database KusakiDB, which correlates the information of three databases, OrthoDB, UniProt and RefSeq and ranks the sequences by protein existence level (which supports the evidence for the existence of a protein). Therefore, the more annotated sequences propagate their annotation layers based on the sequence similarity parameters. Also, sequence alignment methods use a different algorithm than InterProScan, so it is expected that their results will differ. 

Hope it helped.
